### ISSUE TITLE
Syntax errors in controller code doesn't throw errors

### ISSUE THREAD

**Issue by shankie-codes** [scottie1984/swagger-express-router#1]
Hey @scottie1984 – great project... but I've run into one wee issue – in my controllers that I require like so:

```js
  const controllers = {
    'user.controller': require('./controllers/user.controller'),
    'event.controller': require('./controllers/event.controller'),
  };
```

They don't throw errors when the app runs for syntax errors in in the controllers. Instead, `swagger-express-router simply doesn't `console.log` its usual `SETTING UP ROUTE /api/v1/events/:id delete event.controller.deleteEvent` – it simply causes the route to 404.

Any idea how we can get these syntax errors to propagate through the console rather than just being suppressed?

**Comment by shankie-codes** [comment]
I'd have a whirl myself at debugging but I find Ramda a bit intimidating!

**Comment by scottie1984** [comment]
Hey - i think there must be a problem parsing your Swagger file. Any change you could send your swagger file and set-up code for this module?

**Comment by shankie-codes** [comment]
I see why you'd think that, but the swagger file parses fine with a minimal test controller, but fails when I try to introduce more complicated code in my controller (in my case, I'm making another API call to Auth0). 

At any rate, my setup is:

```js
SwaggerParser.dereference(__dirname + '/swagger/swagger.yaml')
.then(function(api) {
  // Replace the hostname with the one set in env vars
  api.host = process.env.API_HOSTNAME;

  // Serve the Swagger spec on /api-docs
  app.use('/api-docs', (req, res) => res.json(api));

  const controllers = {
    'user.controller': require('./controllers/user.controller'),
    'event.controller': require('./controllers/event.controller'),
  };

  swagger.setUpRoutes(controllers, app, api, true);
});
```
...where I'm using SwaggerParser to dereference the YAML – and the outputted JSON (`api`, in this code) looks like [this](https://gist.github.com/shankie-san/0213468e656e121cf88c9f76003dda26).

And then my user controller... 

If I do something really basic, like:

```js
exports.listUsers = async function(req, res) {
  res.json('something');
}
```

... it sets up the routes, but when I try to do something that has an error (as I believe my `auth0management` file does), like this:

```js
const mongoose = require('mongoose');
import { managementClient } from '../util/auth0Management';

exports.listUsers = async function(req, res) {
  const users = await managementClient.getUsers();
  res.json(users);
}
```
... it doesn't set up the routes, and consequently Express 404s the route (oh, and that's with the same Swagger doc).

Obviously, I've got to work out what the beef is with my Auth0 API wrapper, but that's quite tricky to do when I can't get at the route.

Thanks for your help!

**Comment by shankie-codes** [comment]
I guess it's also worth adding that if I introduce an arbitrary syntax error in any of the controllers, `swagger-express-router` also doesn't set up the routes.

**Comment by shankie-codes** [comment]
Ah! Even more information – a syntax error in one controller also prevents controllers for other routes being set up.

**Comment by scottie1984** [comment]
ok - so just to summarise, any type of syntax error in any controller will stop all routes from being attached?

Ideal outcome is that this module reports the error rather than supress?

**Comment by shankie-codes** [comment]
Looks like, as far as I can tell. I probably could have said that at the start 😉

**Comment by scottie1984** [comment]
I have been struggling to recreate this. Can you provide an example of the type of error?

**Comment by scottie1984** [comment]
Ok - I think the problem is due to the fact you are setting up the module through a promise and the syntax error is being swallowed. Could the swagger dereference be performed synchronously?

**Comment by shankie-codes** [comment]
Indeed you're right @scottie1984 – I've never encountered that before! Apparently it's a [thing](http://jamesknelson.com/are-es6-promises-swallowing-your-errors/). I guess I'll have to install Bluebird just for this!

**Comment by shankie-codes** [comment]
Thanks for your help @scottie1984 – even though it wasn't to do with `swagger-express-router`!
